@extends('layouts.frontend')

@section('title', 'Beranda')

@section('content')
<section class="hero-section"><div class="container"><div class="row align-items-center"><div class="col-lg-6"><h1 class="mb-4">Selamat Datang di<br><span style="color:#3498db;">EkstraKurikuler</span></h1><p class="mb-4">Informasi kegiatan ekstrakurikuler Mahasiswa. Temukan berbagai kegiatan menarik untuk mengembangkan bakat dan minat siswa.</p><div class="d-flex gap-3"><a href="{{ route('about') }}" class="btn btn-primary-custom"><i class="bi bi-info-circle me-2"></i>Tentang</a><a href="{{ route('public.ekstrakurikuler') }}" class="btn btn-outline-custom"><i class="bi bi-calendar-event me-2"></i>Lihat Kegiatan</a></div></div><div class="col-lg-6 text-center"><div class="bg-white rounded-4 p-5 shadow-sm d-inline-block"><div style="width:200px;height:200px;background:linear-gradient(135deg,#2c3e50,#3498db);border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto;"><i class="bi bi-calendar-event display-1 text-white"></i></div><h4 class="mt-3">EkstraKurikuler</h4><p class="text-muted">Kegiatan Siswa</p></div></div></div></div></section>

<section class="py-5"><div class="container"><div class="text-center mb-5"><h2 class="section-title">Kegiatan <span class="highlight">Ekstrakurikuler</span></h2><p class="text-muted">Berbagai kegiatan menarik untuk siswa</p></div><div class="row g-4">@forelse($ekstrakurikuler->take(4) as $item)<div class="col-md-3"><div class="card card-hover">@if($item->gambar)<img src="{{ asset($item->gambar) }}" class="card-img-top" style="height:180px;object-fit:cover;">@else<div class="card-img-top bg-light d-flex align-items-center justify-content-center" style="height:180px;"><i class="bi bi-calendar-event display-3 text-muted"></i></div>@endif<div class="card-body"><h6>{{ $item->nama_kegiatan }}</h6><p class="small text-muted">{{ $item->hari }} • {{ $item->waktu }}</p><span class="badge bg-primary">{{ $item->pembina }}</span></div></div></div>@empty<div class="col-12 text-center"><p class="text-muted">Belum ada kegiatan ekstrakurikuler.</p></div>@endforelse</div><div class="text-center mt-4"><a href="{{ route('public.ekstrakurikuler') }}" class="btn btn-primary-custom">Lihat Semua <i class="bi bi-arrow-right ms-2"></i></a></div></div></section>

<section class="py-5" style="background:linear-gradient(135deg,#2c3e50,#3498db);"><div class="container text-center text-white"><h2 class="display-5 fw-bold">Kembangkan Bakat & Minat!</h2><p class="mb-4 opacity-75">Ikuti berbagai kegiatan ekstrakurikuler di sekolah</p><a href="{{ route('public.ekstrakurikuler') }}" class="btn btn-light btn-lg rounded-pill px-5"><i class="bi bi-calendar-event me-2"></i>Lihat Kegiatan</a></div></section>
@endsection
